application:
  subdomain: coolmonitor
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://coolmonitor:3333/
services:
  coolmonitor:
    # upstream: docker.io/star7th/coolmonitor:latest@sha256:8db9a1471252d421c24960560126b0f4f96206f9a594210056e5b99270c58242
    image: registry.lazycat.cloud/czyt/star7th/coolmonitor:74d57281bede24b7
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DOCKER_SETUP=true
    binds:
      - /lzcapp/var/data:/app/data
