application:
  subdomain: coolmonitor
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://coolmonitor:3333/
services:
  coolmonitor:
    # upstream: docker.io/star7th/coolmonitor:latest@sha256:2b6946b185438a5d3623774a79efbb9c8d6329454d527670013ac8eb51a95b91
    image: registry.lazycat.cloud/czyt/star7th/coolmonitor:89193c2af378c4fe
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DOCKER_SETUP=true
    binds:
      - /lzcapp/var/data:/app/data
