lzc-sdk-version: "0.1"
name: coolmonitor
package: cloud.lazycat.app.coolmonitor
version: 0.0.1
description: 高颜值的监控工具
homepage: https://github.com/star7th/coolmonitor
author: star7th
application:
    subdomain: coolmonitor
    background_task: true
    public_path:
        - /
    routes:
        - /=http://coolmonitor:3333/
services:
    coolmonitor:
        image: docker.1ms.run/star7th/coolmonitor:latest
        environment:
            - NODE_ENV=production
            - PORT=3333
            - DOCKER_SETUP=true
        binds:
            - /lzcapp/var/data:/app/data
